ConsultaDadosCadastrais/Controllers/ConsultaController.cs
using ConsultaDadosCadastrais.Classes;
using ConsultaDadosCadastrais.Models;
using ConsultaDadosCadastrais.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using PagedList;
using System.Web.UI.HtmlControls;

namespace ConsultaDadosCadastrais.Controllers
{
    public class ConsultaController : Controller
    {


        public ActionResult Index()
        {
            ViewBag.Filtro = CriaListaMenu();
            ClaimsModel claimsModel = new ClaimsModel();
            claimsModel = Session["Claims"] as ClaimsModel;
            Session["nomeUsuario"] = claimsModel.UserName;
            //455
            return View();
                        
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Pesquisar(VmConsulta mdl)
        {
            if (ModelState.IsValid)
            {
                LimparVarTemporarias();

                if (mdl != null)
                {
                    if (mdl.Filtro.Dado != null)
                    {
                        mdl.Filtro.Pagina = 1;
                        mdl.Filtro.QuantidadeLinhas = 10;
                        mdl.Filtro.Paginacao = true;
                        //Preciso Chamar a classe Consulta 
                        Pesquisa pq = new Pesquisa();
                        List<ConsultaProdataModel> lst = new List<ConsultaProdataModel>();
                        lst = pq.ConsultaDados(mdl.Filtro);


                        if (lst.Count > 0)
                        {
                            TempData["ListaResultado"] = lst;
                            Session["FiltroConsulta"] = mdl.Filtro;

                        }
                    }                   
                }

            }
            ViewBag.Filtro = CriaListaMenu();
            return View("Index");
        }

        private void LimparVarTemporarias()
        {
            TempData["ListaResultado"] = null;
            Session["FiltroConsulta"] = null;
            Session["Pagina"] = null;
            Session["Linhas"] = null;
            Session["PaginaRequisitaca"] = null;            
        }

        [HttpGet]
        public PartialViewResult GetResultadoPesquisa()
        {

            List<ConsultaProdataModel> consulta = new List<ConsultaProdataModel>();
            consulta = TempData["ListaResultado"] as List<ConsultaProdataModel>;

            if (consulta != null)
            {
                Pesquisa pq = new Pesquisa();
                ConsultaQtdeProdataModel qtde = new ConsultaQtdeProdataModel();
                qtde = pq.ConsultaQtdeDados(Session["FiltroConsulta"] as DadosConsultaProdataModel);

                int pagina = Convert.ToInt32(Session["Pagina"]);
                int Linhas = Convert.ToInt32(Session["Linhas"]);
                if (pagina == 0) { pagina = 1; }
                if (Linhas == 0) { Linhas = 10; }


                if (qtde.Registros > 0) 
                {
                    ViewBag.Encontradas = qtde.Registros / Linhas;
                }

                return PartialView("_PartConsulta", consulta.ToPagedList(1, Linhas));
            }
            else
            {
                return PartialView("_PartConsulta");
            }
            //return PartialView(consulta);
        }

        [HttpGet]
        public ActionResult SelecionarPagina(int? pagina)
        {

            DadosConsultaProdataModel dados = new DadosConsultaProdataModel();
            dados = Session["FiltroConsulta"] as DadosConsultaProdataModel;
            dados.Pagina = (int)pagina;
            Pesquisa pq = new Pesquisa();
            List<ConsultaProdataModel> lst = new List<ConsultaProdataModel>();
            lst = pq.ConsultaDados(dados);
            if (lst.Count > 0)
            {
                TempData["ListaResultado"] = lst;
                Session["Pagina"] = pagina;
                Session["Linhas"] = 10;
                Session["PaginaRequisitaca"] = pagina;
            }
            ViewBag.Filtro = CriaListaMenu();
            return View("Index");
        }

        [HttpGet]
        public ActionResult CarregarDados(int idUsuario, int pagina = 1)
        {
            CadastroProdataModel cadastroProdata = null;
            if (ModelState.IsValid)
            {
                if (Session["AccessToken"] != null)
                {
                    if (idUsuario > 0)
                    {
                        //Preciso Chamar a classe Consulta 
                        Pesquisa pq = new Pesquisa();
                        cadastroProdata = new CadastroProdataModel();
                        cadastroProdata = pq.GetDadosUsuario(idUsuario);
                        // Formatando Dados
                        cadastroProdata.Cpf = RotinasFormatacao.FormataCpf(cadastroProdata.Cpf);
                        if (cadastroProdata.Endereco != null)
                        {
                            cadastroProdata.Endereco.Cep = RotinasFormatacao.FormataCep(cadastroProdata.Endereco.Cep);
                        }
                        cadastroProdata.Telefone = RotinasFormatacao.FormataTelefone(cadastroProdata.Telefone);
                        cadastroProdata.Celular = RotinasFormatacao.FormataTelefone(cadastroProdata.Celular);
                        cadastroProdata.Recado = RotinasFormatacao.FormataTelefone(cadastroProdata.Recado);
                        Session["PaginaRequisitaca"] = pagina;
                    }

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            ViewBag.Pagina = pagina;
            return View("DadosCadastrais", cadastroProdata);
        }



        private SelectList CriaListaMenu()
        {
            ItemFiltro it1 = new ItemFiltro();
            it1.Id = 1;
            it1.Descricao = "CPF";

            ItemFiltro it2 = new ItemFiltro();
            it2.Id = 2;
            it2.Descricao = "NOME";

            ItemFiltro it3 = new ItemFiltro();
            it3.Id = 3;
            it3.Descricao = "NOME DA MÃE";


            List<ItemFiltro> lst = new List<ItemFiltro>();
            lst.Add(it1);
            lst.Add(it2);
            lst.Add(it3);


            return new SelectList(lst, "Id", "Descricao");

        }
    }
}

ConsultaDadosCadastrais/Views/Consulta/DadosCadastrais.cshtml
@model ConsultaDadosCadastrais.Models.CadastroProdataModel

@section csspersonalizado {

    <link href="~/Content/print.css" rel="stylesheet">
}

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dados Cadastrais</h2>
<hr />
<br />


<div class="form-horizontal">
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>@Html.LabelFor(m => m.Nome) : </label>
            @Html.DisplayFor(m => m.Nome)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>@Html.LabelFor(m => m.Sexo) : </label>
            @Html.DisplayFor(m => m.Sexo)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>@Html.LabelFor(m => m.Nascimento) : </label>
            @Html.DisplayFor(m => m.Nascimento)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>Estado Civil: </label>
            @Html.DisplayFor(m => m.EstadoCivil)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>Pai: </label>
            @Html.DisplayFor(m => m.Pai)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>Mãe : </label>
            @Html.DisplayFor(m => m.Mae)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>CPF : </label>
            @Html.DisplayFor(m => m.Cpf)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>RG : </label>
            @Html.DisplayFor(m => m.Rg)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>Nº Certidão: </label>
            @Html.DisplayFor(m => m.Certidao)
        </div>
    </div>
    <br />
    <h3>Endereço</h3>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>Endereço: </label>
            @Html.DisplayFor(m => m.Endereco.rua)
            <label>Nº </label>
            @Html.DisplayFor(m => m.Endereco.Numero)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>Complemento: </label>
            @Html.DisplayFor(m => m.Endereco.Complemento)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>Bairro: </label>
            @Html.DisplayFor(m => m.Endereco.Bairro)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>Cep: </label>
            @Html.DisplayFor(m => m.Endereco.Cep)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>Cidade: </label>
            @Html.DisplayFor(m => m.Endereco.Cidade)
        </div>
    </div>
    <br />
    <h3>Contato</h3>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>E-mail: </label>
            @Html.DisplayFor(m => m.Email)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>Tel. Celuar: </label>
            @Html.DisplayFor(m => m.Celular)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>Tel. Residêncial: </label>
            @Html.DisplayFor(m => m.Telefone)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <label>Tel. Recado: </label>
            @Html.DisplayFor(m => m.Recado)
        </div>
    </div>
</div>
<br />


<div class="no-print">
    <button type="button" value="imprimir" onclick="window.print();">Imprimir</button>
    <br />
    <br />
    <p>
        @Ajax.ActionLink("Voltar", "SelecionarPagina", "Consulta", new
        {
            pagina = ViewBag.Pagina
        }, new AjaxOptions
        {
        HttpMethod = "GET",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "PostDetalle",
        OnBegin = "onBeginAjax",
        OnComplete = "onCompleteAjax",
        OnSuccess = "onSuccessAjax",
        OnFailure = "onFailureAjax"
        }, new { id = "IdLink", @class = "miClaseCss" })
    </p>

</div>






@section Scripts {
    <script>
        $(document).ready(function () {
            $("#telefone").inputmask("mask", { "mask": "(99) 9999-99999" });
            $("#cpf").inputmask("mask", { "mask": "999.999.999-99" }, { reverse: true });
            $("#cep").inputmask("mask", { "mask": "99999-999" });
            $("#nascimento").inputmask("mask", { "mask": "99/99/9999" });
            $("#preco").inputmask("mask", { "mask": "999.999,99" }, { reverse: true });
            $("#valor").inputmask("mask", { "mask": "#.##9,99" }, { reverse: true });
        });
    </script>
}

ConsultaDadosCadastrais/Views/Consulta/Index.cshtml
@model ConsultaDadosCadastrais.Models.ViewModels.VmConsulta

@section csspersonalizado {
   
}

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h2>Consulta Dados Cadastrais</h2>
    <h6>Usuário: @HttpContext.Current.Session["nomeUsuario"].ToString() </h6>

    @using (Html.BeginForm("Pesquisar", "Consulta", FormMethod.Post))
    {
        //cria a tag do formulário
        @Html.AntiForgeryToken() // previne o ataque CSRF
        @Html.ValidationSummary(true)
        if (@ViewBag.Message != null)
        {
            <div style="border:1px solid red">
                @ViewBag.Message
            </div>
        }
        <form class="form-horizontal" role="form">

            <table class="table">
                <tr>
                    <td class="text-info"><b>Filtrar:</b></td>
                    <td>
                        @Html.DropDownListFor(m => m.Filtro.Tipo, new SelectList(ViewBag.Filtro.Items, "Id", "Descricao"), new { @class = "form-control form-control-custom", @style = "width:500px;" })
                    </td>
                </tr>
                <tr>
                    <td class="text-info"><b>Dados:</b></td>
                    <td>@Html.TextBoxFor(model => model.Filtro.Dado, new { @class = "form-control form-control-custom", @style = "width:1000px;" })</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <input type="submit" id="search" title="Pesquisar" value="Pesquisar" />
                    </td>
                </tr>
            </table>
        </form>



        <div id="divResultado">
                @{Html.RenderPartial("_PartConsulta"); }
            
        </div>




    }
</div>


@section scripts {

    <script type="text/javascript">
            /* script para carregar as promoções */
        $.get('@Url.Action("GetResultadoPesquisa", "Consulta")', function (data) {
            $("#divResultado").html(data);
            });
    </script>
}

ConsultaDadosCadastrais/Views/Consulta/_PartConsulta.cshtml
@model PagedList.IPagedList<ConsultaDadosCadastrais.Models.ConsultaProdataModel>
@using PagedList.Mvc;



<div class="grid" style="margin-left :5px" id="grid">

    @if (Model != null)
    {
        <div class="grid">
            <table class="table table-bordered table-responsive table-hove">
                <thead>
                    <tr>
                        <th align="center">@Html.DisplayName("Nome")</th>
                        <th align="center">@Html.DisplayName("Mãe")</th>
                        <th align="center">@Html.DisplayName("Nascimento")</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var mdl in Model)
                    {
                        <tr>
                            <td align="justify">
                                @Ajax.ActionLink(@mdl.Nome, "CarregarDados", "Consulta", new { idUsuario = mdl.Codigo.ToString(), pagina = Session["PaginaRequisitaca"] }, new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    InsertionMode = InsertionMode.Replace,
                                    UpdateTargetId = "PostDetalle",
                                    OnBegin = "onBeginAjax",
                                    OnComplete = "onCompleteAjax",
                                    OnSuccess = "onSuccessAjax",
                                    OnFailure = "onFailureAjax"
                                }, new { id = "IdLink", @class = "miClaseCss" })
                            </td>
                            <td align="justify">
                                @mdl.Mae
                            </td>
                            <td align="center">
                                @mdl.Nascimento.ToShortDateString()
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div>
                @{
                    if (Model.TotalItemCount > 1)
                    {
                        int? pag = Convert.ToInt32(@Session["Pagina"]);
                        if (pag == 0)
                        {
                            pag = 1;
                        }

                        if (Convert.ToInt32(Session["PaginaRequisitaca"]) > 1)
                        {
                            pag = Convert.ToInt32(Session["PaginaRequisitaca"]);
                            <td>Página @pag.ToString() de @ViewBag.Encontradas</td>
                        }
                        else
                        {
                            <td>Página @pag.ToString() de @ViewBag.Encontradas</td>
                        }

                        <br />
                        <br />

                        if (pag > 1)
                        {


                            @Ajax.ActionLink("< Anterior", "SelecionarPagina", "Consulta", new { pagina = pag - 1 }, new AjaxOptions
                            {
                                HttpMethod = "GET",
                                InsertionMode = InsertionMode.Replace,
                                UpdateTargetId = "PostDetalle",
                                OnBegin = "onBeginAjax",
                                OnComplete = "onCompleteAjax",
                                OnSuccess = "onSuccessAjax",
                                OnFailure = "onFailureAjax"
                            }, new { id = "IdLink", @class = "miClaseCss" })

                        }

                        if (pag > 1)
                        {
                            <td> | | </td>
                        }

                        if (ViewBag.Encontradas > 1)
                        {
                            if (pag < ViewBag.Encontradas)
                            {
                                @Ajax.ActionLink("Próxima >", "SelecionarPagina", "Consulta", new { pagina = pag + 1 }, new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    InsertionMode = InsertionMode.Replace,
                                    UpdateTargetId = "PostDetalle",
                                    OnBegin = "onBeginAjax",
                                    OnComplete = "onCompleteAjax",
                                    OnSuccess = "onSuccessAjax",
                                    OnFailure = "onFailureAjax"
                                }, new { id = "IdLink", @class = "miClaseCss" })

                            }
                        }
                    }


                }

            </div>
        </div>
    }

</div>

@section scripts {

    <!-- JQUERY UNOBTRUSIVE PARA Ajax.ActionLink() -->
    @Scripts.Render("~/bundles/jqueryajax")

    <!-- AL COMENZAR LA LLAMADA AJAX -->
    <script>
        var onBeginAjax = function () {
            alert("Begin");
        };
    </script>

    <!-- AL FINALIZAR LA LLAMADA AJAX -->
    <script>
        var onCompleteAjax = function () {
            alert("Complete");
        };
    </script>

    <!-- SE EJECUTA SI TODO FUE BIEN -->
    <script>
        var onSuccessAjax = function () {
            alert("Success");
        };
    </script>

    <!-- SE EJECUTA SI TODO FUE BIEN -->
    <script>
        var onFailureAjax = function () {
            alert("Failure");
        };
    </script>
}